In [22]:
import pandas as pd
import numpy as np

In [23]:
#1
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [24]:
a1 = a.reshape(2, 6)
a2 = a.reshape(6, 2)
a3 = a.reshape(3, 4)
a4 = a.reshape(4, 3)
a5 = a.reshape(1, 12)
a6 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [25]:
a1 = a.reshape(4, -1)
a2 = a.reshape(6, -1)
a3 = a.reshape(12, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 3)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [26]:
#  Задание 4 
#  Вопрос: Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#  Ответ: Нельзя. Первое измерение строка, второе столб.

In [47]:
#  Задание 5
a = np.random.randn(3, 4)
a

array([[ 1.56361987,  0.19606282,  0.09677462,  1.20761747],
       [ 0.88462765, -0.39708778, -0.50252588, -0.45094564],
       [-0.6720612 , -1.57962821,  1.07637198, -1.64565892]])

In [51]:
#  Задание 6
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [53]:
#  Задание 7
b = np.arange(20, 0, -2).reshape(1, 10)
b
#  Вопрос: В чем разница между массивами a и b?
#  Ответ: a - одномерный массив, b - двумерный массив

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [65]:
# Задание 8
a = np.zeros((4, 1))
b = np.ones((6, 1))
v = np.vstack((a, b))
print(v.size)

10


In [70]:
# Задание 9
a=np.arange(0, 12)
A=a.reshape(4,3)
At=A.T
B = np.dot(A, At)
B.size
#  Вопрос: Получится ли вычислить обратную матрицу для матрицы B
#  Ответ: Нет. Не получится. т.к матрица B сингулярна

16

In [72]:
#Задание 10
np.random.seed(42)


In [83]:
#Задание 11
c=np.random.randint(0, 16, 16)
c


array([ 7, 13,  6, 11,  8, 13,  7,  4, 15, 12,  1, 14,  4,  7,  9,  8])

In [85]:
#Задание 12
C=c.reshape(4,4)
D=B+C*10
D


array([[ 75, 144,  83, 142],
       [ 94, 180, 156, 162],
       [173, 206, 159, 352],
       [ 72, 192, 302, 382]])

In [86]:
d=np.linalg.det(D)
d


157936800.00000036

In [89]:
r=np.linalg.matrix_rank(D)
r

4

In [90]:
D_inv=np.linalg.inv(D)
D_inv


array([[-0.03040406,  0.01889579,  0.01188247, -0.00766066],
       [ 0.02551451, -0.00636786, -0.00774994,  0.00035736],
       [-0.02096535,  0.01534297,  0.00035179,  0.00096254],
       [ 0.00948126, -0.01249069,  0.00137751,  0.00312112]])

In [ ]:
#Задание 13
D_inv=np.where(D_inv<0, 0,1)
D_inv


In [91]:
E=np.where(D_inv==1, B, C)
E

array([[ 7, 13,  6, 11],
       [ 8, 13,  7,  4],
       [15, 12,  1, 14],
       [ 4,  7,  9,  8]])